server:
  port: 8081
spring:
  application:
    name: cloud-prometheus-sample-v1
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 这里只暴露普罗米修斯和健康检查的端点
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
info:
  application-name: ${spring.application.name}
  server-port: ${server.port}